export const statusLabels: Record<string, string> = {
  pending: "Pending",
  queued: "Queued",
  scanning: "Scanning",
  paused: "Paused",
  completed: "Completed",
  completed_with_errors: "Completed with errors",
  ready: "Ready",
  ignored: "Ignored",
  invalid: "Needs attention",
  downloading: "Downloading",
  converting: "Converting",
  sending: "Sending",
  sent: "Sent",
  failed: "Failed",
  cancelled: "Cancelled",
  sent_unconfirmed: "Sent — unconfirmed",
  verification_required: "Verification required",
  verified: "Verified",
  rejected: "Rejected",
  unknown: "Unknown",
  action_required: "Action required",
};
